### ISSUE TITLE
Make the default text in input boxes lighter

### ISSUE THREAD

**Issue by Elepert** [olinlibrary/abe-web-frontend#35]
Just design wise it's nice to have the text be lighter than full on black to differentiated nicely from what's default and what's actually been inputed by the user.

**Comment by kylecombes** [comment]
Issue on Chrome, not Firefox.

**Comment by kylecombes** [comment]
Actually Firefox just wasn't listening to the CSS. Regardless, resolved in c8b4e3f74916b6cffc97e6f27e8b611e2224ecef.
