### ISSUE TITLE
Datetime picker doesn't update with sliders

### ISSUE THREAD

**Issue by newsch** [olinlibrary/abe-web-frontend#45]
To replicate:
*Add Event* > *Start* > *Move slider*
The text input box won't update with the new time displayed in the box itself
![image](https://user-images.githubusercontent.com/10699964/28373314-03306aba-6c70-11e7-8e04-7cb446779a52.png)

**Comment by kylecombes** [comment]
See kylecombes/input-text#2

**Comment by kylecombes** [comment]
Resolved in kylecombes/input-moment@af7110b3fe9e36e6217d5774e3b5617ca72cafb9
