### ISSUE TITLE
New label picker for editing events doesn't load labels

### ISSUE THREAD

**Issue by newsch** [olinlibrary/abe-web-frontend#65]
Editing an event doesn't load the labels
![image](https://user-images.githubusercontent.com/10699964/28637846-e54a82fa-7210-11e7-844d-ede63f701706.png)
![image](https://user-images.githubusercontent.com/10699964/28637869-f83f4940-7210-11e7-913a-315bc128188e.png)

**Comment by audreywl** [comment]
Resolved before I even noticed this issue in 8c76c7d95ff4a4e1134e357bb8f1557e77f86061
