### ISSUE TITLE
After Selecting "All" labels, loading event details, and returning to calendar, default categories are selected.

### ISSUE THREAD

**Issue by dalewl** [olinlibrary/abe-web-frontend#72]
Need to have a way to view event details, without resetting the selected event categories.
Select all, before clicking event ![Before clicking event](https://user-images.githubusercontent.com/11560346/28728429-3d1c2366-738e-11e7-8175-b416ba8d7db4.png)
After clicking event ![After clicking event](https://user-images.githubusercontent.com/11560346/28728428-3d1be608-738e-11e7-8017-977aae749b34.png)
Event details clicked ![Event details clicked](https://user-images.githubusercontent.com/11560346/28728431-3d486fde-738e-11e7-95cb-d84cf668d087.png)
Default categories selected ![Default categories selected](https://user-images.githubusercontent.com/11560346/28728695-31baca62-738f-11e7-90f3-11e332b29cf7.png)

**Comment by kylecombes** [comment]
I believe this was fixed with 9daa75256c0ec475f7504c324159019ba2188d5b (labels used to be fetched on every page load, which would explain this behavior).
